export const NOTES = [
    {
        id:1,
        text:'A',
        alternativeText:'',
        value:'A'
    },
    {
        id:2,
        text:'A#',
        alternativeText:'Bb',
        value:'A#'
    },
    {
        id:3,
        text:'B',
        alternativeText:'',
        value:'B'
    },
    {
        id:4,
        text:'C',
        alternativeText:'',
        value:'C'
    },
    {
        id:5,
        text:'C#',
        alternativeText:'Db',
        value:'C#'
    },
    {
        id:6,
        text:'D',
        alternativeText:'',
        value:'D'
    },
    {
        id:7,
        text:'D#',
        alternativeText:'Eb',
        value:'D#'
    },
    {
        id:8,
        text:'E',
        alternativeText:'',
        value:'E'
    },
    {
        id:9,
        text:'F',
        alternativeText:'',
        value:'F'
    },
    {
        id:10,
        text:'F#',
        alternativeText:'Gb',
        value:'F#'
    },
    {
        id:11,
        text:'G',
        alternativeText:'',
        value:'G'
    },
    {
        id:12,
        text:'G#',
        alternativeText:'Ab',
        value:'G#'
    }
]