import {Key} from './Key'

export const KEYS:Key[] = [
    {
        id:1,
        text:'A',
        value:'A',
        note1:'A',
        note2:'B',
        note3:'C#',
        note4:'D',
        note5:'E',
        note6:'F#',
        note7:'G#',
        note8:'A'
    },
    {
        id:2,
        text:'B',
        value:'B',
        note1:'B',
        note2:'C#',
        note3:'D#',
        note4:'E',
        note5:'F#',
        note6:'G#',
        note7:'A#',
        note8:'B'
    },
    {
        id:3,
        text:'C',
        value:'C',
        note1:'C',
        note2:'D',
        note3:'E',
        note4:'F',
        note5:'G',
        note6:'A',
        note7:'B',
        note8:'C'
    },
    {
        id:4,
        text:'D',
        value:'D',
        note1:'D',
        note2:'E',
        note3:'F#',
        note4:'G',
        note5:'A',
        note6:'B',
        note7:'C#',
        note8:'D'
    },
    {
        id:5,
        text:'E',
        value:'E',
        note1:'E',
        note2:'F#',
        note3:'G#',
        note4:'A',
        note5:'B',
        note6:'C#',
        note7:'D#',
        note8:'E'
    },
    {
        id:6,
        text:'F',
        value:'F',
        note1:'F',
        note2:'G',
        note3:'A',
        note4:'Bb',
        note5:'C',
        note6:'D',
        note7:'E',
        note8:'F'
    },
    {
        id:7,
        text:'G',
        value:'G',
        note1:'G',
        note2:'A',
        note3:'B',
        note4:'C',
        note5:'D',
        note6:'E',
        note7:'F#',
        note8:'G'
    }
]