import {Chord} from './Chord'

export const CHORDS: Chord[] = [
    {
        id:1,
        key:'A',
        text:'A',
        degree:1,
        degreeText:'I',
        first:'A',
        third:'C#',
        fifth:'E'
    },
    {
        id:2,
        key:'A',
        text:'Bm',
        degree:2,
        degreeText:'II',
        first:'B',
        third:'D',
        fifth:'F#'
    },
    {
        id:3,
        key:'A',
        text:'C#m',
        degree:3,
        degreeText:'III',
        first:'C#',
        third:'E',
        fifth:'G#'
    },
    {
        id:4,
        key:'A',
        text:'D',
        degree:4,
        degreeText:'IV',
        first:'D',
        third:'F#',
        fifth:'A'
    },
    {
        id:5,
        key:'A',
        text:'E',
        degree:5,
        degreeText:'V',
        first:'E',
        third:'G#',
        fifth:'B'
    },
    {
        id:6,
        key:'A',
        text:'F#m',
        degree:6,
        degreeText:'VI',
        first:'F#',
        third:'A',
        fifth:'C#'
    },
    {
        id:7,
        key:'A',
        text:'G#dim',
        degree:7,
        degreeText:'VII',
        first:'G#',
        third:'B',
        fifth:'D'
    },
    {
        id:8,
        key:'B',
        text:'B',
        degree:1,
        degreeText:'I',
        first:'B',
        third:'D#',
        fifth:'F#'
    },
    {
        id:9,
        key:'B',
        text:'C#m',
        degree:2,
        degreeText:'II',
        first:'C#',
        third:'E',
        fifth:'G#'
    },
    {
        id:10,
        key:'B',
        text:'D#m',
        degree:3,
        degreeText:'III',
        first:'D#',
        third:'F#',
        fifth:'A#'
    },
    {
        id:11,
        key:'B',
        text:'E',
        degree:4,
        degreeText:'IV',
        first:'E',
        third:'G#',
        fifth:'B'
    },
    {
        id:12,
        key:'B',
        text:'F#',
        degree:5,
        degreeText:'V',
        first:'F#',
        third:'A#',
        fifth:'C#'
    },
    {
        id:13,
        key:'B',
        text:'G#m',
        degree:6,
        degreeText:'VI',
        first:'G#',
        third:'B',
        fifth:'D#'
    },
    {
        id:14,
        key:'B',
        text:'A#dim',
        degree:7,
        degreeText:'VII',
        first:'A#',
        third:'C#',
        fifth:'E'
    },
    {
        id:15,
        key:'C',
        text:'C',
        degree:1,
        degreeText:'I',
        first:'C',
        third:'E',
        fifth:'G'
    },
    {
        id:16,
        key:'C',
        text:'D',
        degree:2,
        degreeText:'II',
        first:'D',
        third:'F',
        fifth:'A'
    },
    {
        id:17,
        key:'C',
        text:'Em',
        degree:3,
        degreeText:'III',
        first:'E',
        third:'G',
        fifth:'B'
    },
    {
        id:18,
        key:'C',
        text:'F',
        degree:4,
        degreeText:'IV',
        first:'F',
        third:'A',
        fifth:'C'
    },
    {
        id:19,
        key:'C',
        text:'G',
        degree:5,
        degreeText:'V',
        first:'G',
        third:'B',
        fifth:'D'
    },
    {
        id:20,
        key:'C',
        text:'Am',
        degree:6,
        degreeText:'VI',
        first:'A',
        third:'C',
        fifth:'E'
    },
    {
        id:21,
        key:'C',
        text:'Bdim',
        degree:7,
        degreeText:'VII',
        first:'B',
        third:'D',
        fifth:'F'
    }
]